name             'chef_probe'
maintainer       'Raintank, Inc.'
maintainer_email 'cookbooks@raintank.io'
license          'Apache 2.0'
description      'Installs/Configures chef_probe'
long_description 'Installs/Configures chef_probe'
version          '0.2.0'

depends 'logrotate', '~> 1.9.1'
depends 'chef_base', '~> 0.1.0'
